#!/usr/local/bin/python3
# $OpenBSD$
#
# Helper script for Akita Reticulum rc.d service to generate PF anchor rules
# based on the Reticulum configuration file.

import sys
import argparse
import logging
import yaml
import os

# Default Reticulum port (used by AutoInterface, UDPInterface if not specified)
DEFAULT_RNS_UDP_PORT = 4242

logger = logging.getLogger(__name__)


def sanitize_comment(val):
    if val is None:
        return ""
    return str(val).replace('\n', ' ').replace('\r', ' ')

def configure_logging(debug=False):
    """Configure module logger to write to stderr."""
    if logger.handlers:
        # already configured; just set level
        logger.setLevel(logging.DEBUG if debug else logging.INFO)
        return
    handler = logging.StreamHandler(sys.stderr)
    fmt = "%(levelname)s: %(message)s"
    handler.setFormatter(logging.Formatter(fmt))
    logger.addHandler(handler)
    logger.propagate = False
    logger.setLevel(logging.DEBUG if debug else logging.INFO)

def is_valid_port(port_val):
    """ Check if a value is a valid TCP/UDP port """
    try:
        port = int(port_val)
        return 1 <= port <= 65535
    except (ValueError, TypeError):
        return False

def generate_rules(config_path, debug=False):
    """Parses the Reticulum config and prints PF rules to stdout."""
    # Ensure logging is configured (helps when called programmatically)
    if not logger.handlers:
        configure_logging(debug)

    # Validate config path is absolute and exists
    if not os.path.isabs(config_path):
        logger.error(f"Config path must be absolute: {config_path}")
        sys.exit(1)
    
    # Check file exists and is readable
    if not os.path.isfile(config_path):
        logger.error(f"Config file not found: {config_path}")
        sys.exit(1)
    
    if not os.access(config_path, os.R_OK):
        logger.error(f"Config file is not readable: {config_path}")
        sys.exit(1)
    
    try:
        with open(config_path, 'r', encoding='utf-8') as f:
            config = yaml.safe_load(f) # Use safe_load
    except FileNotFoundError:
        logger.error(f"Config file not found: {config_path}")
        sys.exit(1)
    except yaml.YAMLError as e:
        logger.error(f"Failed to parse YAML config {config_path}: {e}")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Unexpected error reading config {config_path}: {e}")
        sys.exit(1) 

    if not isinstance(config, dict):
        logger.error(f"Invalid config format in {config_path} - expected a dictionary.")
        sys.exit(1)

    interfaces = config.get('interfaces', [])
    if not isinstance(interfaces, list):
        logger.error(f"Invalid config format: 'interfaces' is not a list.")
        sys.exit(1) 

    print(f"# Auto-generated PF rules based on {config_path}")
    print(f"# Generated by: {os.path.basename(__file__)}")
    print("# ---")

    rules_generated = False
    for iface_config in interfaces:
        if not isinstance(iface_config, dict):
            logger.warning(f"Skipping invalid interface entry (not a dict): {iface_config}")
            continue

        # Check top-level 'enabled' flag for the interface block
        if not iface_config.get('enabled', True):
             logger.debug(f"Skipping disabled interface: {iface_config.get('name', 'unnamed')}")
             continue

        # Check interface-specific 'pf_managed' flag (defaults to True if not present)
        if not iface_config.get('pf_managed', True):
            logger.info(f"Skipping PF rule generation for interface (pf_managed: false): {iface_config.get('name', 'unnamed')}")
            continue

        iface_type = sanitize_comment(iface_config.get('type')) if iface_config.get('type') else None
        iface_name = sanitize_comment(iface_config.get('name', 'unnamed'))
        iface_dev = sanitize_comment(iface_config.get('device')) if iface_config.get('device') else None

        try:
            # --- AutoInterface ---
            if iface_type == 'AutoInterface':
                rule_comment = f"# {iface_type} ({iface_name}) discovery ports"
                # AutoInterface requires 29716 and 42671 for discovery/traffic.
                print(f"pass in quick proto udp from any to any port {{ 29716, 42671 }} {rule_comment}")
                print(f"pass out quick proto udp from any port {{ 29716, 42671 }} to any {rule_comment}")
                rules_generated = True
                logger.debug(f"Generated UDP rules for {iface_type} ({iface_name}) on discovery ports")

            # --- UDPInterface ---
            elif iface_type == 'UDPInterface':
                udp_port = iface_config.get('port', DEFAULT_RNS_UDP_PORT)
                if not is_valid_port(udp_port):
                    logger.warning(f"Skipping {iface_type} ({iface_name}) - invalid port: {udp_port}")
                    continue

                target_host = sanitize_comment(iface_config.get('target_host')) if iface_config.get('target_host') else None
                target_port = iface_config.get('target_port', udp_port)
                group = sanitize_comment(iface_config.get('group')) if iface_config.get('group') else None

                # Basic rule allows broadcast/multicast/unicast listen on the port
                # Specifying 'on device' might be too restrictive if device isn't always known/used by pf
                # Let pf match based on destination IP/port primarily.
                rule_comment = f"# {iface_type} ({iface_name}) port {udp_port}"
                if target_host:
                     rule_comment += f" -> {target_host}:{target_port}"
                if group:
                     rule_comment += f" group {group}"

                # Allow incoming packets to the listen port
                print(f"pass in quick proto udp from any to any port {udp_port} {rule_comment}")
                # Allow outgoing packets originating from the listen port (replies/broadcasts)
                # Using 'keep state' might be better for replies if pf is stateful.
                print(f"pass out quick proto udp from any port {udp_port} to any {rule_comment}")
                rules_generated = True
                logger.debug(f"Generated UDP rules for {iface_type} ({iface_name}) on port {udp_port}")

            # --- TCPInterface ---
            elif iface_type == 'TCPInterface':
                listen_port = iface_config.get('listen_port')
                target_host = sanitize_comment(iface_config.get('target_host')) if iface_config.get('target_host') else None
                target_port = iface_config.get('target_port')

                if listen_port:
                    if not is_valid_port(listen_port):
                        logger.warning(f"Skipping {iface_type} ({iface_name}) - invalid listen_port: {listen_port}")
                        continue
                    # Rule for listening TCP socket
                    bind_ip = sanitize_comment(iface_config.get('bind_ip', 'any')) # Default listen on all IPs
                    # Validate bind_ip to prevent injection (basic check)
                    if bind_ip != 'any' and not bind_ip.replace('.', '').replace(':', '').replace('/', '').replace('%', '').isalnum():
                        logger.warning(f"Skipping {iface_type} ({iface_name}) - invalid bind_ip format: {bind_ip}")
                        continue
                    to_spec = f"to {bind_ip}" if bind_ip != 'any' else "to any"
                    print(f"pass in quick proto tcp from any {to_spec} port {listen_port} keep state # {iface_type} listen ({iface_name}) port {listen_port}")
                    # Outgoing replies handled by stateful rule above
                    rules_generated = True
                    logger.debug(f"Generated TCP listen rule for {iface_type} ({iface_name}) on port {listen_port}")
                elif target_host and is_valid_port(target_port):
                    # Outgoing connections don't need specific 'pass in' rules usually.
                    # An outgoing rule might be needed if default policy is block.
                    logger.info(f"Outgoing-only TCPInterface ({iface_name} to {target_host}:{target_port}) typically doesn't require generated PF rules unless default policy blocks outgoing.")
                else:
                    logger.warning(f"Skipping {iface_type} ({iface_name}) - invalid/incomplete configuration.")


            # --- TUNInterface ---
            elif iface_type == 'TUNInterface':
                if iface_dev:
                    # Validate device name to prevent injection
                    # Device names should be alphanumeric with possible numbers
                    if not iface_dev.replace('_', '').replace('-', '').isalnum():
                        logger.warning(f"Skipping TUNInterface ({iface_name}) - invalid device name: {iface_dev}")
                        continue
                    # Basic rule: allow all traffic IN and OUT on the TUN interface.
                    # Assumes filtering happens elsewhere or isn't needed here.
                    print(f"pass quick on {iface_dev} # {iface_type} ({iface_name}) device {iface_dev}")
                    rules_generated = True
                    logger.debug(f"Generated TUN rule for {iface_type} ({iface_name}) on device {iface_dev}")
                else:
                     logger.warning(f"Skipping TUNInterface ({iface_name}) - missing 'device'.")

            # Add other interface types like RNodeInterface if they need specific PF handling
            # e.g., RNodeInterface often uses SerialInterface underneath, no pf rules needed directly.

        except Exception as e:
            logger.warning(f"Error processing interface {iface_name} ({iface_type}): {e}")

    if not rules_generated:
        print("# No specific PF rules generated based on enabled and managed interfaces.")

    print("# ---")
    print("# Note: Review these rules carefully. They are basic allowances and may")
    print("# need adjustment based on your specific network topology and security")
    print("# requirements (e.g., restricting 'from any', using specific interfaces).")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Generate PF rules from Reticulum config')
    parser.add_argument('-c', '--config', help='Path to reticulum config file', metavar='FILE')
    parser.add_argument('--debug', action='store_true', help='Enable debug logging to stderr')
    parser.add_argument('positional_config', nargs='?', help='Path to reticulum config file (positional)')
    args = parser.parse_args()

    config_path = args.config or args.positional_config
    if not config_path:
        parser.print_usage()
        sys.exit(1)

    configure_logging(args.debug)
    generate_rules(config_path, debug=args.debug)
